### ISSUE TITLE
Surrounding Cyrillic word with quotes changes the initial word

### ISSUE THREAD

**Issue by VKondakoff** [blackCauldron7/surround.nvim#25]
Hi!

Surrounding Cyrillic word with quotes changes the initial word. This does not happens with English text.

Here is a short video:

https://user-images.githubusercontent.com/230824/137976339-cedba7e6-d797-4ef6-aec5-799e8fb9abe2.mov

I'm visually selected the word and pressing `s'`. Here are some Russian words for you to test: `тест тест тест`.
Can you reproduce this?
(macOS, Neovim nightly, latest Surround)

**Comment by blackCauldron7** [comment]
Do other surround plugins work fine?

**Comment by VKondakoff** [comment]
Yes. Just tried [this one](https://github.com/tpope/vim-surround), it has no problems with Cyrillic both in motion and visual modes:
<img width="364" alt="Снимок экрана 2021-10-20 в 00 37 20" src="https://user-images.githubusercontent.com/230824/137994386-b2fa5db0-89b5-4868-bdc9-a2886fdc5902.png">

**Comment by VKondakoff** [comment]
Can this be a Unicode issue? https://github.com/neovim/neovim/issues/14281

**Comment by echasnovski** [comment]
I've encountered the same issue when working on [mini.surround](https://github.com/echasnovski/mini.nvim/blob/main/lua/mini/surround.lua). The reason indeed was that `<` and `>` marks return *index of the first byte* in the line. This is ok for the left surrounding (as it should be inserted before first byte). However, this breaks right surrounding (as it should be inserted after last byte of symbol).

I managed to implement 'find last byte of symbol' [like this](https://github.com/echasnovski/mini.nvim/blob/4a71086e69d613a07f11cdd078dfec5b9572debe/lua/mini/surround.lua#L517-L534). It uses the fact that `vim.str_utfindex()` has this behavior: "An {index} in the middle of a UTF-8 sequence is rounded upwards to the end of that sequence."

So a little bit of playing with this project code lead to this.
[In 'utils.lua'](https://github.com/blackCauldron7/surround.nvim/blob/4018f676edfb37ea69b2ab01e80600f694d216b5/lua/surround/utils.lua#L79-L87):
```lua
local function get_visual_pos()
  local start = vim.api.nvim_buf_get_mark(0, "<")
  local start_line = start[1]
  local start_col = start[2] + 1

  local _end = vim.api.nvim_buf_get_mark(0, ">")
  local end_line = _end[1]
  local end_l = vim.fn.getline(end_line)
  local end_col = vim.str_byteindex(
    end_l,
    -- Use `math.min()` because it might lead to 'index out of range' error
    -- when mark is positioned at the end of line (that extra space which is
    -- selected when selecting with `v$`)
    vim.str_utfindex(end_l, math.min(#end_l, _end[2] + 1))
  )
  return start_line, start_col, end_line, end_col
end
```
And [in 'init.lua'](https://github.com/blackCauldron7/surround.nvim/blob/4018f676edfb37ea69b2ab01e80600f694d216b5/lua/surround/init.lua#L213):
```lua
line = string.insert(line, end_col + 1, space .. char_pairs[CLOSING])
```

I am not sure, may be this will break something else, but at least it passes test from first post of this issue. Hope it helps.

**Comment by blackCauldron7** [comment]
@echasnovski thanks for the snippet. Does mini.surround have all features of surround.nvim if not would you wanna merge it into mini.nvim and deprecate this?

**Comment by echasnovski** [comment]
Well, that is hard to tell. It has different setup process:
- Mappings are by default "sandwich" type. User can change each mapping manually inside `require('mini.surround').setup()`.
- It currently doesn't have a customized surroundings. It has "function", "tag", "interactive" (from user input), pre-configured brackets and everything else is a single-symbol surroundings.
- Everything is dot-repeatable.

So it may have much of the functionality of your plugin, but maybe in a different form. I don't plan to update it any time soon. It feels more or less feature-full to me (may be someday allow custom "extension" surroundings, like "latex document", etc.).

**Comment by blackCauldron7** [comment]
sure that makes sense can you point me to the code or give me some hints on how you made everything dot repeatable?

**Comment by echasnovski** [comment]
I believe, it consists from two parts:
- Every action (add, delete, replace, find, highlight) is mapped using `<expr>` mapping. Inside it sets appropriate `operatorfunc` and returns `g@`. Here is [operator code](https://github.com/echasnovski/mini.nvim/blob/4a71086e69d613a07f11cdd078dfec5b9572debe/lua/mini/surround.lua#L175-L184) and here are [mappings](https://github.com/echasnovski/mini.nvim/blob/4a71086e69d613a07f11cdd078dfec5b9572debe/lua/mini/surround.lua#L397-L439).
- Every action implementation uses common cache table which is used when [getting surrounding](https://github.com/echasnovski/mini.nvim/blob/4a71086e69d613a07f11cdd078dfec5b9572debe/lua/mini/surround.lua#L811-L856). If cache is empty, user is prompted to enter surrounding which is cached.

**Comment by blackCauldron7** [comment]
should be fixed in latest commit thanks to @echasnovski :). @VKondakoff please close the issue if it works for you.

**Comment by VKondakoff** [comment]
Something still wrong here. I'm receiving an error:
`E15: Invalid expression: ^[gv<80><fd>hlua require'surround'.surround_add()^M`
when trying to perform `viws'` on a word 'test'.

And an error:
`E15: Invalid expression: <80><fd>hset operatorfunc=SurroundAddOperatorMode^Mg@`
when trying to perform 'saft' on the same word.

**Comment by echasnovski** [comment]
@blackCauldron7, it seems that besides formatting and adding changes from my comment you also added `silent = true, expr = true` to all your mappings. If you were trying to follow other comment about dot-repeatability, then, unfortunately, it is not how this works. Expression mappings should be treated entirely different then normal mappings.

**Comment by blackCauldron7** [comment]
Maybe its fixed now.

@echasnovski thanks for the tip. I guess i'll read some more about expr mappings now.

**Comment by VKondakoff** [comment]
Fixed now! @echasnovski, thanks for help!

Other issues: 

1. `ss repeats last surround command.`
Pressing `saiw'` surrounds current word with `'`, but when I move to the next word and press `ss` just nothing happens.

2. `<c-s><char><c-s> will insert both pairs on newlines insert mode.`
Pressing `Ctrl-s'Ctrl-s` in Insert mode inserts this: `'^S'`.

**Comment by blackCauldron7** [comment]
can you please open new issues for each of those and close this one?

**Comment by blackCauldron7** [comment]
ss mapping is not intended to be used with surround add
